# **Matrix Operations**

Name - Soham Kholpaure | Rollno. 23102A0064 | Class - CMPN A

Matrix Formation

In [ ]:
x = matrix( nrow=4, ncol=3, data=c(1:12))
x

     [,1] [,2] [,3]
[1,] 1    5     9
[2,] 2    6    10
[3,] 3    7    11
[4,] 4    8    12

Renaming Rows and Columns

In [ ]:
rownames(x) = c("r1", "r2", "r3", "r4")
x

   [,1] [,2] [,3]
r1 1    5     9
r2 2    6    10
r3 3    7    11
r4 4    8    12

In [ ]:
colnames(x) = c("c1","c2","c3")
x

   c1 c2 c3
r1 1  5   9
r2 2  6  10
r3 3  7  11
r4 4  8  12

Assigning specific numberto all elements

In [ ]:
x = matrix(nrow=4, ncol=2, data=2)
x

     [,1] [,2]
[1,] 2    2
[2,] 2    2
[3,] 2    2
[4,] 2    2

Diagonal Matrix

In [ ]:
d = diag(1, nrow =3, ncol=3)
d

     [,1] [,2] [,3]
[1,] 1    0    0
[2,] 0    1    0
[3,] 0    0    1

In [ ]:
d = diag(5, nrow =3, ncol=3)
d

     [,1] [,2] [,3]
[1,] 5    0    0
[2,] 0    5    0
[3,] 0    0    5

Transpose of matrix

In [ ]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [ ]:
xt = t(x)
xt

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

Sum of Rows & Columns

In [ ]:
x = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [ ]:
rowSums(x)

[1]  6  8 10 12

In [ ]:
colSums(x)

[1] 10 26

Mean of Rows & Columns

In [ ]:
x = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [ ]:
rowMeans(x)

[1] 3 4 5 6

In [ ]:
colMeans(x)

[1] 2.5 6.5

Access to rows, columns or submatrices

In [ ]:
x = matrix(nrow=5, ncol=3, byrow=T, data=1:15)
x

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12
[5,] 13   14   15

In [ ]:
x[3,]

[1] 7 8 9

In [ ]:
x[,2]

[1]  2  5  8 11 14

In [ ]:
x[4:5, 2:3]

     [,1] [,2]
[1,] 11   12
[2,] 14   15

In [ ]:
x[c(1,4), c(1,3)]

     [,1] [,2]
[1,]  1    3
[2,] 10   12

Addition of matrix with a constant

In [ ]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [ ]:
x+5

     [,1] [,2]
[1,]  6    7
[2,]  8    9
[3,] 10   11
[4,] 12   13

Substraction of matrix with constant

In [ ]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [ ]:
x - 5

     [,1] [,2]
[1,] -4   -3
[2,] -2   -1
[3,]  0    1
[4,]  2    3

Multiplication of matrix with constant

In [ ]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [ ]:
5*x

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

Division of matrix

In [ ]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [ ]:
x/2

     [,1] [,2]
[1,] 0.5  1
[2,] 1.5  2
[3,] 2.5  3
[4,] 3.5  4

Addition & Substraction of matrices

In [ ]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
y = matrix(nrow=4, ncol=2, data=1:8, byrow=T)

In [ ]:
x + y

     [,1] [,2]
[1,]  2    4
[2,]  6    8
[3,] 10   12
[4,] 14   16

In [ ]:
x + 4*x

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

In [ ]:
x - y

     [,1] [,2]
[1,] 0    0
[2,] 0    0
[3,] 0    0
[4,] 0    0

In [ ]:
4*x - x

     [,1] [,2]
[1,]  3    6
[2,]  9   12
[3,] 15   18
[4,] 21   24

Multiplication of matrices

In [ ]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
y = matrix(nrow=2, ncol=4, data=11:18, byrow=T)

In [ ]:
x %*% y

     [,1] [,2] [,3] [,4]
[1,]  41   44   47   50
[2,]  93  100  107  114
[3,] 145  156  167  178
[4,] 197  212  227  242

In [ ]:
t(x) %*% x

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [ ]:
x %*% t(x)

     [,1] [,2] [,3] [,4]
[1,]  5   11   17    23
[2,] 11   25   39    53
[3,] 17   39   61    83
[4,] 23   53   83   113

Cross Product of matrix

In [ ]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [ ]:
t(x)

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

In [ ]:
crossprod(x)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

Concatenating matrices

In [ ]:
x = matrix(nrow=3, ncol=2, data=1:6, byrow=T)
y = matrix(nrow=3, ncol=2, data=11:16, byrow=T)

row wise bind

In [ ]:
rbind(x, y)

     [,1] [,2]
[1,]  1    2
[2,]  3    4
[3,]  5    6
[4,] 11   12
[5,] 13   14
[6,] 15   16

column wise bind

In [ ]:
cbind(x,y)

     [,1] [,2] [,3] [,4]
[1,] 1    2    11   12
[2,] 3    4    13   14
[3,] 5    6    15   16

Inverse of matrix

In [ ]:
y = matrix(nrow=2, ncol=2, byrow=T, data=c(84,100,100,120))
y

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [ ]:
solve(y)

     [,1]  [,2]
[1,]  1.50 -1.25
[2,] -1.25  1.05

Eigen Values & Eigen Vectors

In [ ]:
y = matrix(nrow=2, ncol=2, byrow=T, data=c(84,100,100,120))
y

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [ ]:
eigen(y)

eigen() decomposition
$values
[1] 203.6070864   0.3929136

$vectors
          [,1]       [,2]
[1,] 0.6414230 -0.7671874
[2,] 0.7671874  0.6414230

# **Logical Operators**

Use of | & ||

In [ ]:
x = 8
(x<10) || (x<2)

[1] TRUE

In [ ]:
x = 18
(x<10) || (x<2)

[1] FALSE

In [ ]:
x = c(8,18)

(x<10) | (x<2)

[1]  TRUE FALSE

Use of & and &&

In [ ]:
x = 5
(x<10) && (x>2)

[1] TRUE

In [ ]:
x = c(8,18)
(x<10) & (x>2)

[1]  TRUE FALSE

In [ ]:
x = 1:6
(x>2) & (x<5)

[1] FALSE FALSE  TRUE  TRUE FALSE FALSE

Standard logical operation

In [ ]:
x= TRUE
y= FALSE

In [ ]:
x & y

[1] FALSE

In [ ]:
x | y

[1] TRUE

In [ ]:
!x

[1] FALSE

In [ ]:
8 > 7

[1] TRUE

In [ ]:
7>7

[1] FALSE

In [ ]:
8 <= 8

[1] TRUE

In [ ]:
8 != 9

[1] TRUE

In [ ]:
x = c(1,2,3)
y = c(4,5,6)

In [ ]:
x > y

[1] FALSE FALSE FALSE

In [ ]:
x < y

[1] TRUE TRUE TRUE

In [ ]:
x != y

[1] TRUE TRUE TRUE

In [ ]:
isTRUE(8<6)

[1] FALSE

In [ ]:
isTRUE(8>6)

[1] TRUE